create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique not null,avatar_url text,is_admin boolean not null default false,created_at timestamptz default now());
create table if not exists public.posts(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,body text,image_url text,created_at timestamptz default now(),constraint post_content check(nullif(trim(coalesce(body,'')),'') is not null or image_url is not null));
create table if not exists public.likes(post_id uuid references public.posts(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,created_at timestamptz default now(),primary key(post_id,user_id));
create table if not exists public.comments(id uuid primary key default gen_random_uuid(),post_id uuid references public.posts(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,body text not null,created_at timestamptz default now());
alter table public.profiles enable row level security;alter table public.posts enable row level security;alter table public.likes enable row level security;alter table public.comments enable row level security;
create policy "profiles read" on public.profiles for select using(true);
create policy "profile own insert" on public.profiles for insert with check(auth.uid()=id);
create policy "profile own update" on public.profiles for update using(auth.uid()=id);
create policy "posts read" on public.posts for select using(true);
create policy "posts insert" on public.posts for insert with check(auth.uid()=user_id);
create policy "owner admin delete posts" on public.posts for delete using(auth.uid()=user_id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin));
create policy "likes read" on public.likes for select using(true);
create policy "likes own insert" on public.likes for insert with check(auth.uid()=user_id);
create policy "likes own delete" on public.likes for delete using(auth.uid()=user_id);
create policy "comments read" on public.comments for select using(true);
create policy "comments insert" on public.comments for insert with check(auth.uid()=user_id);
create policy "comment owner admin delete" on public.comments for delete using(auth.uid()=user_id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin));
insert into storage.buckets(id,name,public) values('post-images','post-images',true) on conflict(id) do nothing;
create policy "images read" on storage.objects for select using(bucket_id='post-images');
create policy "images upload auth" on storage.objects for insert with check(bucket_id='post-images' and auth.uid() is not null);
